//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XXBoom.MachinaX.BlogX.CmsX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://service.tabula.com/Passport.Customer.asmx")]
        public string CmsX_2_6_0_CustomerWS_PassportX_x0020_Customer_x0020_Services {
            get {
                return ((string)(this["CmsX_2_6_0_CustomerWS_PassportX_x0020_Customer_x0020_Services"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://service.tabula.com/Passport.Admin.asmx")]
        public string CmsX_2_6_0_PassportAdminWS_PassportX_x0020_Admin_x0020_Services {
            get {
                return ((string)(this["CmsX_2_6_0_PassportAdminWS_PassportX_x0020_Admin_x0020_Services"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.ididthatad.com/Access.asmx")]
        public string CmsX_2_6_0_AccessWS_AccessServiceX {
            get {
                return ((string)(this["CmsX_2_6_0_AccessWS_AccessServiceX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.ididthatad.com/User.asmx")]
        public string CmsX_2_6_0_UserWS_UserServiceX {
            get {
                return ((string)(this["CmsX_2_6_0_UserWS_UserServiceX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.ididthatad.com/LinkLog.asmx")]
        public string CmsX_2_6_0_LinkLogWS_LinkLogServiceX {
            get {
                return ((string)(this["CmsX_2_6_0_LinkLogWS_LinkLogServiceX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ididthatad.com/adminx.asmx")]
        public string CmsX_2_6_0_AdminXWS_adminX {
            get {
                return ((string)(this["CmsX_2_6_0_AdminXWS_adminX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.loeries.co.za/DisplayXMenus.asmx")]
        public string CmsX_2_6_0_DisplayXMenusWS_DisplayXMenus {
            get {
                return ((string)(this["CmsX_2_6_0_DisplayXMenusWS_DisplayXMenus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ididthatad.com/DisplayXSite.asmx")]
        public string CmsX_2_6_0_DisplayXSiteWS_SiteDisplayxServiceX {
            get {
                return ((string)(this["CmsX_2_6_0_DisplayXSiteWS_SiteDisplayxServiceX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ididthatad.com/ContentXBlogs.asmx")]
        public string CmsX_2_6_0_ContentXBlogsWS_ContentXBlogs {
            get {
                return ((string)(this["CmsX_2_6_0_ContentXBlogsWS_ContentXBlogs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ididthatad.com/ContentXSpaces.asmx")]
        public string CmsX_2_6_0_ContentXSpacesWS_ContentXSpaces {
            get {
                return ((string)(this["CmsX_2_6_0_ContentXSpacesWS_ContentXSpaces"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ididthatad.com/ContentXMedia.asmx")]
        public string CmsX_2_6_0_ContentXMediaWS_ContentXMedia {
            get {
                return ((string)(this["CmsX_2_6_0_ContentXMediaWS_ContentXMedia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.loeries.co.za/DisplayXLinks.asmx")]
        public string CmsX_2_6_0_DisplayXLinksWS_DisplayXLinks {
            get {
                return ((string)(this["CmsX_2_6_0_DisplayXLinksWS_DisplayXLinks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maxima.xxboom.co.za/ContentXFiles.asmx")]
        public string CmsX_2_6_0_ContentXFilesWS_ContentXFiles {
            get {
                return ((string)(this["CmsX_2_6_0_ContentXFilesWS_ContentXFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://service.tabula.com/Passport.Passport.asmx")]
        public string CmsX_2_6_0_PassportWS_PassportX_x0020_Passport_x0020_Services {
            get {
                return ((string)(this["CmsX_2_6_0_PassportWS_PassportX_x0020_Passport_x0020_Services"]));
            }
        }
    }
}
