//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace XXBoom.MachinaX.BlogX.CmsX.DisplayXSiteWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SiteDisplayxServiceXSoap", Namespace="http://www.clickclickBOOM.com/MachinaX/DisplayX")]
    public partial class SiteDisplayxServiceX : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FormatDisplayXLinksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDisplayXOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMenusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLinksOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPagesOrderedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetThoughtspaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestCustomOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestExceptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SiteDisplayxServiceX() {
            this.Url = global::XXBoom.MachinaX.BlogX.CmsX.Properties.Settings.Default.CmsX_2_6_0_DisplayXSiteWS_SiteDisplayxServiceX;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FormatDisplayXLinksCompletedEventHandler FormatDisplayXLinksCompleted;
        
        /// <remarks/>
        public event GetDisplayXCompletedEventHandler GetDisplayXCompleted;
        
        /// <remarks/>
        public event GetMenusCompletedEventHandler GetMenusCompleted;
        
        /// <remarks/>
        public event GetParentsCompletedEventHandler GetParentsCompleted;
        
        /// <remarks/>
        public event GetMenuCompletedEventHandler GetMenuCompleted;
        
        /// <remarks/>
        public event GetLinksCompletedEventHandler GetLinksCompleted;
        
        /// <remarks/>
        public event DeleteMenuCompletedEventHandler DeleteMenuCompleted;
        
        /// <remarks/>
        public event DeletePageCompletedEventHandler DeletePageCompleted;
        
        /// <remarks/>
        public event DeleteMenuItemCompletedEventHandler DeleteMenuItemCompleted;
        
        /// <remarks/>
        public event AddMenuCompletedEventHandler AddMenuCompleted;
        
        /// <remarks/>
        public event AddMenuItemCompletedEventHandler AddMenuItemCompleted;
        
        /// <remarks/>
        public event EditMenuCompletedEventHandler EditMenuCompleted;
        
        /// <remarks/>
        public event EditMenuItemCompletedEventHandler EditMenuItemCompleted;
        
        /// <remarks/>
        public event GetPagesCompletedEventHandler GetPagesCompleted;
        
        /// <remarks/>
        public event GetPagesOrderedCompletedEventHandler GetPagesOrderedCompleted;
        
        /// <remarks/>
        public event GetPageCompletedEventHandler GetPageCompleted;
        
        /// <remarks/>
        public event AddPageCompletedEventHandler AddPageCompleted;
        
        /// <remarks/>
        public event GetThoughtspaceCompletedEventHandler GetThoughtspaceCompleted;
        
        /// <remarks/>
        public event GetSitesCompletedEventHandler GetSitesCompleted;
        
        /// <remarks/>
        public event GetSiteCompletedEventHandler GetSiteCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event TestNameCompletedEventHandler TestNameCompleted;
        
        /// <remarks/>
        public event TestCustomCompletedEventHandler TestCustomCompleted;
        
        /// <remarks/>
        public event TestErrorCompletedEventHandler TestErrorCompleted;
        
        /// <remarks/>
        public event TestExceptionCompletedEventHandler TestExceptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/FormatDisplayXLinks", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode FormatDisplayXLinks(string blogxID) {
            object[] results = this.Invoke("FormatDisplayXLinks", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void FormatDisplayXLinksAsync(string blogxID) {
            this.FormatDisplayXLinksAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void FormatDisplayXLinksAsync(string blogxID, object userState) {
            if ((this.FormatDisplayXLinksOperationCompleted == null)) {
                this.FormatDisplayXLinksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatDisplayXLinksOperationCompleted);
            }
            this.InvokeAsync("FormatDisplayXLinks", new object[] {
                        blogxID}, this.FormatDisplayXLinksOperationCompleted, userState);
        }
        
        private void OnFormatDisplayXLinksOperationCompleted(object arg) {
            if ((this.FormatDisplayXLinksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatDisplayXLinksCompleted(this, new FormatDisplayXLinksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetDisplayX", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetDisplayX(string blogxID) {
            object[] results = this.Invoke("GetDisplayX", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetDisplayXAsync(string blogxID) {
            this.GetDisplayXAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetDisplayXAsync(string blogxID, object userState) {
            if ((this.GetDisplayXOperationCompleted == null)) {
                this.GetDisplayXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDisplayXOperationCompleted);
            }
            this.InvokeAsync("GetDisplayX", new object[] {
                        blogxID}, this.GetDisplayXOperationCompleted, userState);
        }
        
        private void OnGetDisplayXOperationCompleted(object arg) {
            if ((this.GetDisplayXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDisplayXCompleted(this, new GetDisplayXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetMenus", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetMenus(string blogxID) {
            object[] results = this.Invoke("GetMenus", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetMenusAsync(string blogxID) {
            this.GetMenusAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetMenusAsync(string blogxID, object userState) {
            if ((this.GetMenusOperationCompleted == null)) {
                this.GetMenusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenusOperationCompleted);
            }
            this.InvokeAsync("GetMenus", new object[] {
                        blogxID}, this.GetMenusOperationCompleted, userState);
        }
        
        private void OnGetMenusOperationCompleted(object arg) {
            if ((this.GetMenusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenusCompleted(this, new GetMenusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetParents", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetParents(string blogxID) {
            object[] results = this.Invoke("GetParents", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetParentsAsync(string blogxID) {
            this.GetParentsAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetParentsAsync(string blogxID, object userState) {
            if ((this.GetParentsOperationCompleted == null)) {
                this.GetParentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParentsOperationCompleted);
            }
            this.InvokeAsync("GetParents", new object[] {
                        blogxID}, this.GetParentsOperationCompleted, userState);
        }
        
        private void OnGetParentsOperationCompleted(object arg) {
            if ((this.GetParentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParentsCompleted(this, new GetParentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetMenu", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetMenu(string blogxID, int id) {
            object[] results = this.Invoke("GetMenu", new object[] {
                        blogxID,
                        id});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetMenuAsync(string blogxID, int id) {
            this.GetMenuAsync(blogxID, id, null);
        }
        
        /// <remarks/>
        public void GetMenuAsync(string blogxID, int id, object userState) {
            if ((this.GetMenuOperationCompleted == null)) {
                this.GetMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenuOperationCompleted);
            }
            this.InvokeAsync("GetMenu", new object[] {
                        blogxID,
                        id}, this.GetMenuOperationCompleted, userState);
        }
        
        private void OnGetMenuOperationCompleted(object arg) {
            if ((this.GetMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenuCompleted(this, new GetMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetLinks", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetLinks(string blogxID, int id) {
            object[] results = this.Invoke("GetLinks", new object[] {
                        blogxID,
                        id});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetLinksAsync(string blogxID, int id) {
            this.GetLinksAsync(blogxID, id, null);
        }
        
        /// <remarks/>
        public void GetLinksAsync(string blogxID, int id, object userState) {
            if ((this.GetLinksOperationCompleted == null)) {
                this.GetLinksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinksOperationCompleted);
            }
            this.InvokeAsync("GetLinks", new object[] {
                        blogxID,
                        id}, this.GetLinksOperationCompleted, userState);
        }
        
        private void OnGetLinksOperationCompleted(object arg) {
            if ((this.GetLinksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinksCompleted(this, new GetLinksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/DeleteMenu", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeleteMenu(string blogxID, int id) {
            object[] results = this.Invoke("DeleteMenu", new object[] {
                        blogxID,
                        id});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMenuAsync(string blogxID, int id) {
            this.DeleteMenuAsync(blogxID, id, null);
        }
        
        /// <remarks/>
        public void DeleteMenuAsync(string blogxID, int id, object userState) {
            if ((this.DeleteMenuOperationCompleted == null)) {
                this.DeleteMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMenuOperationCompleted);
            }
            this.InvokeAsync("DeleteMenu", new object[] {
                        blogxID,
                        id}, this.DeleteMenuOperationCompleted, userState);
        }
        
        private void OnDeleteMenuOperationCompleted(object arg) {
            if ((this.DeleteMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMenuCompleted(this, new DeleteMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/DeletePage", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeletePage(string blogxID, int id) {
            object[] results = this.Invoke("DeletePage", new object[] {
                        blogxID,
                        id});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePageAsync(string blogxID, int id) {
            this.DeletePageAsync(blogxID, id, null);
        }
        
        /// <remarks/>
        public void DeletePageAsync(string blogxID, int id, object userState) {
            if ((this.DeletePageOperationCompleted == null)) {
                this.DeletePageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePageOperationCompleted);
            }
            this.InvokeAsync("DeletePage", new object[] {
                        blogxID,
                        id}, this.DeletePageOperationCompleted, userState);
        }
        
        private void OnDeletePageOperationCompleted(object arg) {
            if ((this.DeletePageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePageCompleted(this, new DeletePageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/DeleteMenuItem", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeleteMenuItem(string blogxID, int menuId, int mItemId) {
            object[] results = this.Invoke("DeleteMenuItem", new object[] {
                        blogxID,
                        menuId,
                        mItemId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMenuItemAsync(string blogxID, int menuId, int mItemId) {
            this.DeleteMenuItemAsync(blogxID, menuId, mItemId, null);
        }
        
        /// <remarks/>
        public void DeleteMenuItemAsync(string blogxID, int menuId, int mItemId, object userState) {
            if ((this.DeleteMenuItemOperationCompleted == null)) {
                this.DeleteMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMenuItemOperationCompleted);
            }
            this.InvokeAsync("DeleteMenuItem", new object[] {
                        blogxID,
                        menuId,
                        mItemId}, this.DeleteMenuItemOperationCompleted, userState);
        }
        
        private void OnDeleteMenuItemOperationCompleted(object arg) {
            if ((this.DeleteMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMenuItemCompleted(this, new DeleteMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/AddMenu", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddMenu(string blogxID, string name, string page, string displayValue, string pattern, string ConcatId) {
            object[] results = this.Invoke("AddMenu", new object[] {
                        blogxID,
                        name,
                        page,
                        displayValue,
                        pattern,
                        ConcatId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddMenuAsync(string blogxID, string name, string page, string displayValue, string pattern, string ConcatId) {
            this.AddMenuAsync(blogxID, name, page, displayValue, pattern, ConcatId, null);
        }
        
        /// <remarks/>
        public void AddMenuAsync(string blogxID, string name, string page, string displayValue, string pattern, string ConcatId, object userState) {
            if ((this.AddMenuOperationCompleted == null)) {
                this.AddMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMenuOperationCompleted);
            }
            this.InvokeAsync("AddMenu", new object[] {
                        blogxID,
                        name,
                        page,
                        displayValue,
                        pattern,
                        ConcatId}, this.AddMenuOperationCompleted, userState);
        }
        
        private void OnAddMenuOperationCompleted(object arg) {
            if ((this.AddMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMenuCompleted(this, new AddMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/AddMenuItem", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddMenuItem(string blogxID, int menuId, string name, string page, string displayValue) {
            object[] results = this.Invoke("AddMenuItem", new object[] {
                        blogxID,
                        menuId,
                        name,
                        page,
                        displayValue});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddMenuItemAsync(string blogxID, int menuId, string name, string page, string displayValue) {
            this.AddMenuItemAsync(blogxID, menuId, name, page, displayValue, null);
        }
        
        /// <remarks/>
        public void AddMenuItemAsync(string blogxID, int menuId, string name, string page, string displayValue, object userState) {
            if ((this.AddMenuItemOperationCompleted == null)) {
                this.AddMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMenuItemOperationCompleted);
            }
            this.InvokeAsync("AddMenuItem", new object[] {
                        blogxID,
                        menuId,
                        name,
                        page,
                        displayValue}, this.AddMenuItemOperationCompleted, userState);
        }
        
        private void OnAddMenuItemOperationCompleted(object arg) {
            if ((this.AddMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMenuItemCompleted(this, new AddMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/EditMenu", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode EditMenu(string blogxID, int menuId, string name, string page, string displayValue, string pattern, string concatId) {
            object[] results = this.Invoke("EditMenu", new object[] {
                        blogxID,
                        menuId,
                        name,
                        page,
                        displayValue,
                        pattern,
                        concatId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void EditMenuAsync(string blogxID, int menuId, string name, string page, string displayValue, string pattern, string concatId) {
            this.EditMenuAsync(blogxID, menuId, name, page, displayValue, pattern, concatId, null);
        }
        
        /// <remarks/>
        public void EditMenuAsync(string blogxID, int menuId, string name, string page, string displayValue, string pattern, string concatId, object userState) {
            if ((this.EditMenuOperationCompleted == null)) {
                this.EditMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditMenuOperationCompleted);
            }
            this.InvokeAsync("EditMenu", new object[] {
                        blogxID,
                        menuId,
                        name,
                        page,
                        displayValue,
                        pattern,
                        concatId}, this.EditMenuOperationCompleted, userState);
        }
        
        private void OnEditMenuOperationCompleted(object arg) {
            if ((this.EditMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditMenuCompleted(this, new EditMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/EditMenuItem", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode EditMenuItem(string blogxID, int menuId, int mItemId, string name, string page, string displayValue) {
            object[] results = this.Invoke("EditMenuItem", new object[] {
                        blogxID,
                        menuId,
                        mItemId,
                        name,
                        page,
                        displayValue});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void EditMenuItemAsync(string blogxID, int menuId, int mItemId, string name, string page, string displayValue) {
            this.EditMenuItemAsync(blogxID, menuId, mItemId, name, page, displayValue, null);
        }
        
        /// <remarks/>
        public void EditMenuItemAsync(string blogxID, int menuId, int mItemId, string name, string page, string displayValue, object userState) {
            if ((this.EditMenuItemOperationCompleted == null)) {
                this.EditMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditMenuItemOperationCompleted);
            }
            this.InvokeAsync("EditMenuItem", new object[] {
                        blogxID,
                        menuId,
                        mItemId,
                        name,
                        page,
                        displayValue}, this.EditMenuItemOperationCompleted, userState);
        }
        
        private void OnEditMenuItemOperationCompleted(object arg) {
            if ((this.EditMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditMenuItemCompleted(this, new EditMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetPages", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPages(string blogxID) {
            object[] results = this.Invoke("GetPages", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPagesAsync(string blogxID) {
            this.GetPagesAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetPagesAsync(string blogxID, object userState) {
            if ((this.GetPagesOperationCompleted == null)) {
                this.GetPagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPagesOperationCompleted);
            }
            this.InvokeAsync("GetPages", new object[] {
                        blogxID}, this.GetPagesOperationCompleted, userState);
        }
        
        private void OnGetPagesOperationCompleted(object arg) {
            if ((this.GetPagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPagesCompleted(this, new GetPagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetPagesOrdered", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPagesOrdered(string blogxID, string order) {
            object[] results = this.Invoke("GetPagesOrdered", new object[] {
                        blogxID,
                        order});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPagesOrderedAsync(string blogxID, string order) {
            this.GetPagesOrderedAsync(blogxID, order, null);
        }
        
        /// <remarks/>
        public void GetPagesOrderedAsync(string blogxID, string order, object userState) {
            if ((this.GetPagesOrderedOperationCompleted == null)) {
                this.GetPagesOrderedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPagesOrderedOperationCompleted);
            }
            this.InvokeAsync("GetPagesOrdered", new object[] {
                        blogxID,
                        order}, this.GetPagesOrderedOperationCompleted, userState);
        }
        
        private void OnGetPagesOrderedOperationCompleted(object arg) {
            if ((this.GetPagesOrderedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPagesOrderedCompleted(this, new GetPagesOrderedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetPage", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPage(string blogxID, int pageId) {
            object[] results = this.Invoke("GetPage", new object[] {
                        blogxID,
                        pageId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPageAsync(string blogxID, int pageId) {
            this.GetPageAsync(blogxID, pageId, null);
        }
        
        /// <remarks/>
        public void GetPageAsync(string blogxID, int pageId, object userState) {
            if ((this.GetPageOperationCompleted == null)) {
                this.GetPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPageOperationCompleted);
            }
            this.InvokeAsync("GetPage", new object[] {
                        blogxID,
                        pageId}, this.GetPageOperationCompleted, userState);
        }
        
        private void OnGetPageOperationCompleted(object arg) {
            if ((this.GetPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPageCompleted(this, new GetPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/AddPage", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddPage(string blogxID, string name, string space, string topic, string blog) {
            object[] results = this.Invoke("AddPage", new object[] {
                        blogxID,
                        name,
                        space,
                        topic,
                        blog});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddPageAsync(string blogxID, string name, string space, string topic, string blog) {
            this.AddPageAsync(blogxID, name, space, topic, blog, null);
        }
        
        /// <remarks/>
        public void AddPageAsync(string blogxID, string name, string space, string topic, string blog, object userState) {
            if ((this.AddPageOperationCompleted == null)) {
                this.AddPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPageOperationCompleted);
            }
            this.InvokeAsync("AddPage", new object[] {
                        blogxID,
                        name,
                        space,
                        topic,
                        blog}, this.AddPageOperationCompleted, userState);
        }
        
        private void OnAddPageOperationCompleted(object arg) {
            if ((this.AddPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPageCompleted(this, new AddPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetThoughtspace", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetThoughtspace(string blogxID) {
            object[] results = this.Invoke("GetThoughtspace", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetThoughtspaceAsync(string blogxID) {
            this.GetThoughtspaceAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetThoughtspaceAsync(string blogxID, object userState) {
            if ((this.GetThoughtspaceOperationCompleted == null)) {
                this.GetThoughtspaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetThoughtspaceOperationCompleted);
            }
            this.InvokeAsync("GetThoughtspace", new object[] {
                        blogxID}, this.GetThoughtspaceOperationCompleted, userState);
        }
        
        private void OnGetThoughtspaceOperationCompleted(object arg) {
            if ((this.GetThoughtspaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetThoughtspaceCompleted(this, new GetThoughtspaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetSites", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSites() {
            object[] results = this.Invoke("GetSites", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetSitesAsync() {
            this.GetSitesAsync(null);
        }
        
        /// <remarks/>
        public void GetSitesAsync(object userState) {
            if ((this.GetSitesOperationCompleted == null)) {
                this.GetSitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSitesOperationCompleted);
            }
            this.InvokeAsync("GetSites", new object[0], this.GetSitesOperationCompleted, userState);
        }
        
        private void OnGetSitesOperationCompleted(object arg) {
            if ((this.GetSitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSitesCompleted(this, new GetSitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/GetSite", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSite(string blogxID) {
            object[] results = this.Invoke("GetSite", new object[] {
                        blogxID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiteAsync(string blogxID) {
            this.GetSiteAsync(blogxID, null);
        }
        
        /// <remarks/>
        public void GetSiteAsync(string blogxID, object userState) {
            if ((this.GetSiteOperationCompleted == null)) {
                this.GetSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiteOperationCompleted);
            }
            this.InvokeAsync("GetSite", new object[] {
                        blogxID}, this.GetSiteOperationCompleted, userState);
        }
        
        private void OnGetSiteOperationCompleted(object arg) {
            if ((this.GetSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiteCompleted(this, new GetSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/Test", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/TestName", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestName() {
            object[] results = this.Invoke("TestName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestNameAsync() {
            this.TestNameAsync(null);
        }
        
        /// <remarks/>
        public void TestNameAsync(object userState) {
            if ((this.TestNameOperationCompleted == null)) {
                this.TestNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestNameOperationCompleted);
            }
            this.InvokeAsync("TestName", new object[0], this.TestNameOperationCompleted, userState);
        }
        
        private void OnTestNameOperationCompleted(object arg) {
            if ((this.TestNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestNameCompleted(this, new TestNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/TestCustom", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TestCustom(string Format, string RootName, string ResultName, string CodeName, string DescriptionName) {
            object[] results = this.Invoke("TestCustom", new object[] {
                        Format,
                        RootName,
                        ResultName,
                        CodeName,
                        DescriptionName});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TestCustomAsync(string Format, string RootName, string ResultName, string CodeName, string DescriptionName) {
            this.TestCustomAsync(Format, RootName, ResultName, CodeName, DescriptionName, null);
        }
        
        /// <remarks/>
        public void TestCustomAsync(string Format, string RootName, string ResultName, string CodeName, string DescriptionName, object userState) {
            if ((this.TestCustomOperationCompleted == null)) {
                this.TestCustomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestCustomOperationCompleted);
            }
            this.InvokeAsync("TestCustom", new object[] {
                        Format,
                        RootName,
                        ResultName,
                        CodeName,
                        DescriptionName}, this.TestCustomOperationCompleted, userState);
        }
        
        private void OnTestCustomOperationCompleted(object arg) {
            if ((this.TestCustomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCustomCompleted(this, new TestCustomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/TestError", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TestError() {
            object[] results = this.Invoke("TestError", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TestErrorAsync() {
            this.TestErrorAsync(null);
        }
        
        /// <remarks/>
        public void TestErrorAsync(object userState) {
            if ((this.TestErrorOperationCompleted == null)) {
                this.TestErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestErrorOperationCompleted);
            }
            this.InvokeAsync("TestError", new object[0], this.TestErrorOperationCompleted, userState);
        }
        
        private void OnTestErrorOperationCompleted(object arg) {
            if ((this.TestErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestErrorCompleted(this, new TestErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.clickclickBOOM.com/MachinaX/DisplayX/TestException", RequestNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", ResponseNamespace="http://www.clickclickBOOM.com/MachinaX/DisplayX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TestException() {
            object[] results = this.Invoke("TestException", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TestExceptionAsync() {
            this.TestExceptionAsync(null);
        }
        
        /// <remarks/>
        public void TestExceptionAsync(object userState) {
            if ((this.TestExceptionOperationCompleted == null)) {
                this.TestExceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestExceptionOperationCompleted);
            }
            this.InvokeAsync("TestException", new object[0], this.TestExceptionOperationCompleted, userState);
        }
        
        private void OnTestExceptionOperationCompleted(object arg) {
            if ((this.TestExceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestExceptionCompleted(this, new TestExceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void FormatDisplayXLinksCompletedEventHandler(object sender, FormatDisplayXLinksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatDisplayXLinksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatDisplayXLinksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetDisplayXCompletedEventHandler(object sender, GetDisplayXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDisplayXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDisplayXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetMenusCompletedEventHandler(object sender, GetMenusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetParentsCompletedEventHandler(object sender, GetParentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetMenuCompletedEventHandler(object sender, GetMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetLinksCompletedEventHandler(object sender, GetLinksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DeleteMenuCompletedEventHandler(object sender, DeleteMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DeletePageCompletedEventHandler(object sender, DeletePageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void DeleteMenuItemCompletedEventHandler(object sender, DeleteMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AddMenuCompletedEventHandler(object sender, AddMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AddMenuItemCompletedEventHandler(object sender, AddMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EditMenuCompletedEventHandler(object sender, EditMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EditMenuItemCompletedEventHandler(object sender, EditMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetPagesCompletedEventHandler(object sender, GetPagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetPagesOrderedCompletedEventHandler(object sender, GetPagesOrderedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPagesOrderedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPagesOrderedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetPageCompletedEventHandler(object sender, GetPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AddPageCompletedEventHandler(object sender, AddPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetThoughtspaceCompletedEventHandler(object sender, GetThoughtspaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetThoughtspaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetThoughtspaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetSitesCompletedEventHandler(object sender, GetSitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetSiteCompletedEventHandler(object sender, GetSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TestNameCompletedEventHandler(object sender, TestNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TestCustomCompletedEventHandler(object sender, TestCustomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TestErrorCompletedEventHandler(object sender, TestErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TestExceptionCompletedEventHandler(object sender, TestExceptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestExceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestExceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591